[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
network = "636MP61YRMW4nJNCigzMSRkeuLdxE2oEVYB3aA5HqpbR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
